name: Build and Upload EXE

on:
  schedule:
    - cron: "0 0 * * 0" # Uruchomienie raz w tygodniu w niedzielę o północy
  push:
    branches:
      - master
  workflow_dispatch:

env:
  OS: windows-latest

jobs:
  build:
    runs-on: ${{ env.OS }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r insatallResources.sh
      
    - name: Build EXE
      run: pyinstaller --onefile --name myapp main.py
      
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-exe
        path: dist/myapp.exe
